name: flutter_laundry_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  d_method: ^0.2.6
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.20.2
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
